In [5]:
import numpy as np
np.random.seed(42)  # Reproducible results
arr = np.arange(0, 11, 2)
print(arr)


[ 0  2  4  6  8 10]


In [9]:
A = np.array([[1,2,3],[4,5,6]]) 
print(A)
arr = A.reshape(3, 2)
print(arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [13]:
scores = np.array([85, 92, 78, 95, 88])
h_scores = scores[scores > 90]
print(h_scores) 

[92 95]


In [17]:
data = np.array([1.2, np.nan, 3.4, np.nan, 5.6])
data[np.isnan(data)] = 0
print(data)

[1.2 0.  3.4 0.  5.6]


In [18]:
ages = np.array([25, 30, 28, 35, 22])
min_age = ages.min()
max_age = ages.max()
normalized = (ages - min_age) / (max_age - min_age)
print("original", ages)
print("normalized", normalized)

original [25 30 28 35 22]
normalized [0.23076923 0.61538462 0.46153846 1.         0.        ]
